# Generated by Django 5.2.7 on 2026-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unread_count_for_colaborador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unread_count_for_tecnico',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
