# Generated by Django 5.2.8 on 2025-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_username_mensagem_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
